2025-03-04 06:43:47,175 INFO    MainThread:30108 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-04 06:43:47,175 INFO    MainThread:30108 [wandb_setup.py:_flush():67] Configure stats pid to 30108
2025-03-04 06:43:47,175 INFO    MainThread:30108 [wandb_setup.py:_flush():67] Loading settings from C:\Users\jaygu\.config\wandb\settings
2025-03-04 06:43:47,176 INFO    MainThread:30108 [wandb_setup.py:_flush():67] Loading settings from F:\Semester 8\Introduction to Deep Learning\Assignment_1\wandb\settings
2025-03-04 06:43:47,176 INFO    MainThread:30108 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-04 06:43:47,176 INFO    MainThread:30108 [wandb_init.py:setup_run_log_directory():647] Logging user logs to F:\Semester 8\Introduction to Deep Learning\Assignment_1\wandb\run-20250304_064347-l5mp8b8z\logs\debug.log
2025-03-04 06:43:47,176 INFO    MainThread:30108 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to F:\Semester 8\Introduction to Deep Learning\Assignment_1\wandb\run-20250304_064347-l5mp8b8z\logs\debug-internal.log
2025-03-04 06:43:47,176 INFO    MainThread:30108 [wandb_init.py:init():761] calling init triggers
2025-03-04 06:43:47,176 INFO    MainThread:30108 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'epochs': 100, 'batch_size': 64, 'eval_freq': 10, 'learning_rate': 0.001, 'dataset': 'mnist', 'hidden_size': 64, 'num_layers': 4, 'optimizer': 'sgd', 'weight_init': 'xavier_normal', 'activation': 'relu', 'beta1': 0.9, 'beta2': 0.999, 'epsilon': 1e-08, 'momentum': 0.9, 'weight_decay': 0.0, 'wandb_project': 'Multilayer_FeedForward_Network', 'wandb_entity': 'jay_gupta-indian-institute-of-technology-madras', 'beta': 0.9, '_wandb': {}}
2025-03-04 06:43:47,177 INFO    MainThread:30108 [wandb_init.py:init():784] starting backend
2025-03-04 06:43:47,177 INFO    MainThread:30108 [wandb_init.py:init():788] sending inform_init request
2025-03-04 06:43:47,200 INFO    MainThread:30108 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-04 06:43:47,201 INFO    MainThread:30108 [wandb_init.py:init():803] backend started and connected
2025-03-04 06:43:47,203 INFO    MainThread:30108 [wandb_init.py:init():896] updated telemetry
2025-03-04 06:43:47,614 INFO    MainThread:30108 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-04 06:43:49,075 INFO    MainThread:30108 [wandb_init.py:init():995] starting run threads in backend
2025-03-04 06:43:49,459 INFO    MainThread:30108 [wandb_run.py:_console_start():2377] atexit reg
2025-03-04 06:43:49,459 INFO    MainThread:30108 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-04 06:43:49,460 INFO    MainThread:30108 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-04 06:43:49,460 INFO    MainThread:30108 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-04 06:43:49,468 INFO    MainThread:30108 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-04 06:46:59,032 WARNING MsgRouterThr:30108 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
  File "C:\Users\jaygu\anaconda3\envs\Multilayer_FFNN\lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-04 06:46:59,039 INFO    MsgRouterThr:30108 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
